server:
  port: ${PORT:9092}
spring:
  application:
    name: exchange-rate-service
  datasource:
    url: ${SPRING_DATA_URL:jdbc:h2:mem:testdb}
    driver-class-name: org.h2.Driver
    username: ${DB_USER_NAME:shefkjm}
    password: ${DB_PASSWORD:shef123}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true
cron:
  enabled: ${CRON_ENABLED:true}
  time: ${CRON_EXPRESSION:0/5 * * ? * *}