server:
  port: ${PORT:9092}
spring:
  application:
    name: exchange-rate-service
  datasource:
    url: ${SPRING_DATA_URL:jdbc:mysql://localhost:3306/database?autoReconnect=true&useSSL=false}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME:shefzee}
    password: ${DB_PASSWORD:shef123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

cron:
  enabled: ${CRON_ENABLED:true}
  time: ${CRON_EXPRESSION:0/5 * * ? * *}